### ISSUE TITLE
Improvements ( Todos ? )

### ISSUE THREAD

**Issue by shidhincr** [namshi/keyscannerjs#2]
Want to add ouple of things missing: 

- [ ] The generated file inside the build folder is not minified -- this should be configured in rollup.js.
- [ ] Unit tests  ?
- [ ] Starting the scanning as soon as the class is initialized doesn't seems to be a good pattern. What you think if we create  a `start` method ( which can accept the callback ) and `stop` methods.

**Comment by nikilok** [comment]
Those are all amazing ideas @shidhincr 
I think they are fantastic things to get sorted out.
